# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WakalaRegi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Alamofire'
    pod 'ReachabilitySwift'
    pod 'AlamofireNetworkActivityLogger', '~> 2.0'
    pod 'MagicalRecord'
    pod 'FastEasyMapping', '~> 1.2'
    pod 'IQKeyboardManager'
    pod 'ActionSheetPicker-3.0'
pod 'Tamamushi'
pod 'NVActivityIndicatorView'
pod 'PopupDialog'

  target 'WakalaRegiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WakalaRegiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
